---
abstract: 'Read xlsx spreadsheet files with LibXML'
author:
  - 'Jed Lund <jandrew@cpan.org>'
build_requires:
  Capture::Tiny: 0
  Data::Dumper: 0
  Spreadsheet::ParseExcel: 0
  Test::Moose: 0
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Spreadsheet-XLSX-Reader-LibXML
provides:
  Spreadsheet::XLSX::Reader::LibXML:
    file: lib/Spreadsheet/XLSX/Reader/LibXML.pm
    version: v0.10.6
  Spreadsheet::XLSX::Reader::LibXML::Cell:
    file: lib/Spreadsheet/XLSX/Reader/LibXML/Cell.pm
    version: v0.10.6
  Spreadsheet::XLSX::Reader::LibXML::CellToColumnRow:
    file: lib/Spreadsheet/XLSX/Reader/LibXML/CellToColumnRow.pm
    version: v0.10.6
  Spreadsheet::XLSX::Reader::LibXML::Error:
    file: lib/Spreadsheet/XLSX/Reader/LibXML/Error.pm
    version: v0.10.6
  Spreadsheet::XLSX::Reader::LibXML::FmtDefault:
    file: lib/Spreadsheet/XLSX/Reader/LibXML/FmtDefault.pm
    version: v0.10.6
  Spreadsheet::XLSX::Reader::LibXML::GetCell:
    file: lib/Spreadsheet/XLSX/Reader/LibXML/GetCell.pm
    version: v0.10.6
  Spreadsheet::XLSX::Reader::LibXML::LogSpace:
    file: lib/Spreadsheet/XLSX/Reader/LibXML/LogSpace.pm
    version: v0.10.6
  Spreadsheet::XLSX::Reader::LibXML::ParseExcelFormatStrings:
    file: lib/Spreadsheet/XLSX/Reader/LibXML/ParseExcelFormatStrings.pm
    version: v0.10.6
  Spreadsheet::XLSX::Reader::LibXML::Types:
    file: lib/Spreadsheet/XLSX/Reader/LibXML/Types.pm
    version: v0.10.6
  Spreadsheet::XLSX::Reader::LibXML::UtilFunctions:
    file: lib/Spreadsheet/XLSX/Reader/LibXML/UtilFunctions.pm
    version: v0.10.6
  Spreadsheet::XLSX::Reader::LibXML::XMLReader:
    file: lib/Spreadsheet/XLSX/Reader/LibXML/XMLReader.pm
    version: v0.10.6
  Spreadsheet::XLSX::Reader::LibXML::XMLReader::CalcChain:
    file: lib/Spreadsheet/XLSX/Reader/LibXML/XMLReader/CalcChain.pm
    version: v0.10.6
  Spreadsheet::XLSX::Reader::LibXML::XMLReader::SharedStrings:
    file: lib/Spreadsheet/XLSX/Reader/LibXML/XMLReader/SharedStrings.pm
    version: v0.10.6
  Spreadsheet::XLSX::Reader::LibXML::XMLReader::Styles:
    file: lib/Spreadsheet/XLSX/Reader/LibXML/XMLReader/Styles.pm
    version: v0.10.6
  Spreadsheet::XLSX::Reader::LibXML::XMLReader::Worksheet:
    file: lib/Spreadsheet/XLSX/Reader/LibXML/XMLReader/Worksheet.pm
    version: v0.10.6
  Spreadsheet::XLSX::Reader::LibXML::XMLReader::XMLToPerlData:
    file: lib/Spreadsheet/XLSX/Reader/LibXML/XMLReader/XMLToPerlData.pm
    version: v0.10.6
requires:
  Archive::Zip: 0
  Carp: 0
  DateTime::Format::Flexible: 0
  DateTimeX::Format::Excel: v0.12.0
  File::Temp: 0
  Moose: 0
  Moose::Role: 0
  MooseX::HasDefaults::RO: 0
  MooseX::ShortCut::BuildInstance: v1.8.0
  MooseX::StrictConstructor: 0
  OLE::Storage_Lite: 0
  Type::Coercion: 0
  Type::Library: 0.046
  Type::Tiny: 0
  Type::Utils: 0
  Types::Standard: 0
  XML::LibXML::Reader: 0
  lib: 0
  perl: 5.010
  strict: 0
  version: 0
  warnings: 0
resources:
  bugtracker: https://github.com/jandrew/Spreadsheet-XLSX-Reader-LibXML/issues
  homepage: https://github.com/jandrew/Spreadsheet-XLSX-Reader-LibXML
  repository: https://github.com/jandrew/Spreadsheet-XLSX-Reader-LibXML.git
version: v0.10.6
x_authority: cpan:JANDREW
